### ISSUE TITLE
bug in checksort.c [PULL REQUEST]

### ISSUE THREAD

**Issue by erplefoo** [defuse/crackstation-hashdb#1]
Since the current and max structs are not initialized in main(), the checksort program would often tell me an index was not sorted -- but when run over and over, tell me it was sometimes.

Adding memset(&current,0,sizeof(current)) and memset(&max,0,sizeof(max)) fixed this.

If you are still maintaining this, shall I submit a patch? (I also added checks on the fread() calls to quiet down GCC warnings)

**Comment by defuse** [comment]
@erplefoo Oops, sorry I forgot about this. The usual way to submit a patch on GitHub is to fork the project and submit a pull request. However, pasting it into email is just as good. When I get some time (probably not for a long time), I'll review and apply the patch, thanks!

**Comment by erplefoo** [comment]
I figured I forgot something. No rush :)

On Sun, Mar 1, 2015 at 2:41 AM, Taylor Hornby <notifications@github.com>
wrote:

> @erplefoo <https://github.com/erplefoo> Oops, sorry I forgot about this.
> The usual way to submit a patch on GitHub is to fork the project and submit
> a pull request. However, pasting it into email is just as good. When I get
> some time (probably not for a long time), I'll review and apply the patch,
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/defuse/crackstation-hashdb/issues/1#issuecomment-76588099>
> .
>



-- 
Sean

**Comment by defuse** [comment]
Applied the patch, great work!
